default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  ROOT_FOLDER: .
  DOTNET_CONFIGURATION: Debug

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd $ROOT_FOLDER
    - dotnet restore
    - dotnet build --no-restore --configuration $DOTNET_CONFIGURATION

test:
  stage: test
  script:
    - cd $ROOT_FOLDER
    - dotnet test 
    - dotnet test --no-build --configuration $DOTNET_CONFIGURATION --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  dependencies:
    - build_job
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
